/**
 * @(#) Product.java 1.0 13th, Sep 2013
 * 
 */
package edu.cmu.boyuanli.model;

/**
 * 
 * The class Product is the model class for a product in shopping.com website
 * it contains a static counter to assign number for the result generated by each
 * instance of ShoppingDotComAnalyzer
 * It contains a toString method for print the result stored in itself
 * 
 * @author Boyuan Li, CMU
 * @version 1.0 13th, Sep 2013
 * @since JDK6.0
 */
public class Product {
	private static int counter = 1;
	
	private int number;
	private String productName;
	private String productPrice;
	private String productShippingPrice;
	private String productVendor;

	public Product(String productName, String productPrice,
			String productShippingPrice, String productVendor) {
		super();
		this.productName = productName;
		this.productPrice = productPrice;
		this.productShippingPrice = productShippingPrice;
		this.productVendor = productVendor;
		number = counter++;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductPrice() {
		return productPrice;
	}

	public void setProductPrice(String productPrice) {
		this.productPrice = productPrice;
	}

	public String getProductShippingPrice() {
		return productShippingPrice;
	}

	public void setProductShippingPrice(String productShippingPrice) {
		this.productShippingPrice = productShippingPrice;
	}

	public String getProductVendor() {
		return productVendor;
	}

	public void setProductVendor(String productVendor) {
		this.productVendor = productVendor;
	}

	public String toString(){
		return 	"\n"+ "Product Number: " + number + "\n" +
				"Title/Product Name: " + productName + "\n" +
				"Price of the product: " + productPrice + "\n" +
				"Shipping Price: " + productShippingPrice + "\n" +
				"Vendor: " + productVendor + 
				"\n";
	}
}
